# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-02 04:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='By_File_Extension_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=50)),
                ('lines', models.TextField()),
                ('file_type', models.CharField(max_length=12)),
                ('ui_path', models.TextField()),
                ('quick_summary', models.TextField()),
                ('notes', models.TextField()),
                ('related_files', models.TextField()),
                ('includes_and_imports', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Original_Grep_By_Line_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=50)),
                ('line', models.IntegerField()),
                ('casing', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Src_Files_Master_List',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=50)),
                ('lines', models.TextField()),
                ('file_type', models.CharField(max_length=12)),
                ('comment_subset', models.TextField()),
                ('front_end_subset', models.TextField()),
            ],
        ),
    ]
