# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-02 04:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='by_file_extension_list',
            name='includes_and_imports',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='by_file_extension_list',
            name='lines',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='by_file_extension_list',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='by_file_extension_list',
            name='quick_summary',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='by_file_extension_list',
            name='related_files',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='by_file_extension_list',
            name='ui_path',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='original_grep_by_line_list',
            name='line',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='src_files_master_list',
            name='comment_subset',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='src_files_master_list',
            name='front_end_subset',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='src_files_master_list',
            name='lines',
            field=models.TextField(blank=True, null=True),
        ),
    ]
